### ISSUE TITLE
index-158aa048.js:40 TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by TobinXu** [shenjunru/react-fiber-keep-alive#14]
![image](https://github.com/shenjunru/react-fiber-keep-alive/assets/19850188/ea8a55be-cfce-4b56-b3f4-bb7546c1b037)
index-158aa048.js:40 TypeError: Cannot read properties of null (reading '1')
    at useGlobalCache (index-158aa048.js:135:11474)
    at useStyleRegister (index-158aa048.js:136:1933)
    at index-158aa048.js:176:6380
    at index-158aa048.js:176:8278
    at InternalSelect (index-158aa048.js:329:11394)
    at Xh (index-158aa048.js:38:20793)
    at Zi (index-158aa048.js:40:1612)
    at Wk (index-158aa048.js:40:47955)
    at Vk (index-158aa048.js:40:41504)
    at Uk (index-158aa048.js:40:41429)

 "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-fiber-keep-alive": "^0.7.1",
  "react-router": "^6.22.3",
  "react-router-dom": "^6.22.3",

**Comment by TobinXu** [comment]
![image](https://github.com/shenjunru/react-fiber-keep-alive/assets/19850188/dec2d0c2-36c3-4d83-809c-42c52716a1bf)

**Comment by TobinXu** [comment]
@emotion/css 发现是和cssinjs使用会报错
